id: P003195
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18664
  title: ཟས་རིགས་ཀྱི་བདེ་འཇགས་དང་འཕྲོད་བསྟེན།
  author: ''
  volumes:
    1f7721d7a0ee46278216c513544ac757:
      image_group_id: I8LS18666
      title: ''
      volume_number: 1
      total_pages: 261
      base_file: v001.txt
