id: I997C5387
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:23:03+00:00'
last_modified: '2022-06-07T18:19:48.355737+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18664
  title: ཟས་རིགས་ཀྱི་བདེ་འཇགས་དང་འཕྲོད་བསྟེན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    48CC:
      image_group_id: I8LS18666
      title: ''
      total_pages: 261
      order: 1
      base_file: 48CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
